### ISSUE TITLE
Found an error and have a proposed fix

### ISSUE THREAD

**Issue by adelevie** [cloudfoundry-community/cf-meteor-buildpack#4]
I love that this buildpack automagically sets the `MONGO_URL`, but I'm finding its current implementation inflexible:

``` bash
export MONGO_URL=`echo $VCAP_SERVICES | $jq '."mongodb-2.4"[0].credentials.url'`
```

The Mongo version is hardcoded into the `jq` selector. I wonder if this could be re-written as something like:

``` bash
export MONGO_URL=`echo $VCAP_SERVICES | $jq '."mongodb-*"[0].credentials.ur*'`
```

I implemented a quick and dirty [fix](https://github.com/adelevie/cf-meteor-buildpack/blob/master/bin/release#L11) that works in my organization, [18F](https://18f.gsa.gov), but perhaps we should coalesce around a more robust solution?

Thoughts, @afeld, @dlapiduz?

**Comment by afeld** [comment]
Just for more background, our Mongo service creates a `VCAP_SERVICES` entry that looks like this (obfuscated):

``` json
{
 "VCAP_SERVICES": {
  "mongodb-new": [
   {
    "credentials": {
     "hostname": "1.1.1.1",
     "password": "password",
     "port": "32781",
     "ports": {
      "27017/tcp": "32781",
      "28017/tcp": "32780"
     },
     "uri": "mongodb://user:password@1.1.1.1:32781",
     "username": "user"
    },
    "label": "mongodb-new",
    "name": "meteor-mongo",
    "plan": "free",
    "tags": [
     "mongo"
    ]
   }
  ]
 }
}
```

Not sure why it's called `mongodb-new`, but to cover both this and the hardcoded version issue, our thinking was to simply look for the first `VCAP_SERVICES` key that starts with "mongo". Note that ours also uses a `uri` key rather than `url`. Turns out doing wildcard matching of keys in `jq` is kind of a pain in the butt:

``` bash
jq 'to_entries|map(select(.key|test("mongo")))[0]|.value[0].credentials|if .url then .url else .uri end'
```

Note this requires `jq` 1.5 for the `test()` functionality, which is only a release candidate. Honestly, it might be easier to write a little Node script to generate the `MONGO_URL`.

/cc @csterwa @jsloyer (Are you the maintainers? Seems that no one is Watching the repo.)

**Comment by afeld** [comment]
Asked about simplifying the `jq` expression here: https://github.com/stedolan/jq/issues/863

**Comment by afeld** [comment]
One more thing: we figured that the buildpack shouldn't overwrite the `MONGO_URL` environment variable if it's already present.
